name: Compliance

on:
  pull_request:
  
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+.x"
      - "v[0-9]+"
      
  schedule:
    - cron: "0 * * * *" # Runs hourly
    
  workflow_dispatch:

jobs:
  compliance:
    uses: ghostwriter/compliance/.github/workflows/compliance-reusable.yml@main
